---
# Machine specs
scsi_disk_layout:
  scsi0: "vm-storage:60,format=raw,discard=on,ssd=1"
amount_of_memory: 32768
number_of_vcpus: 18
ip_range:
  - start: 10.24.3.150
    end: 10.24.3.152
starting_number: 1
vm_name: prod-carrier
vm_description: "Production Shuttle Carrier"
