---
# Machine specs
scsi_disk_layout:
  scsi0: "vm-storage:80,format=raw,discard=on,ssd=1"
  scsi1: "vm-storage:2560,format=raw,discard=on,ssd=1"
amount_of_memory: 65536
number_of_vcpus: 16
ip_range:
  - start: 10.24.3.30
    end: 10.24.3.32
starting_number: 1
vm_name: prod-ehi-api-db
vm_description: "Production EHI API Database node"
