---
# Machine specs
scsi_disk_layout:
  scsi0: "vm-storage:50,format=raw"
amount_of_memory: 32768
number_of_vcpus: 48
ip_range:
  - start: 10.24.0.70
    end: 10.24.0.77
starting_number: 1
vm_name: prod-ehi-edge
vm_description: "Production EHI Edge-UR node"
