---
# Machine specs
scsi_disk_layout:
  scsi0: "vm-storage:300,format=raw,discard=on,ssd=1"
amount_of_memory: 8192
number_of_vcpus: 8
ip_range:
  - start: 10.24.3.235
    end: 10.24.3.235
starting_number: 1
vm_name: prod-garage
vm_description: "Production GarageHQ S3"