---
# Machine specs
scsi_disk_layout:
  scsi0: "vm-storage:50,format=raw,discard=on,ssd=1"
amount_of_memory: 32768
minimum_memory: 8192
number_of_vcpus: 48
ip_range:
  - start: 10.24.0.80
    end: 10.24.0.87
starting_number: 1
vm_name: prod-ehi-edge-urid
vm_description: "Production EHI Edge-URID node"
