---
# Machine specs
scsi_disk_layout:
  scsi0: "vm-storage:100,format=raw,discard=on,ssd=1"
amount_of_memory: 131072
minimum_memory: 16384
number_of_vcpus: 48
ip_range:
  - start: 10.24.0.151
    end: 10.24.0.152
starting_number: 1
vm_name: prod-phos-k8s-wxl
vm_description: "Production Phosphophyllite Kubernetes Worker node, Xtra Large"
