---
# Machine specs
scsi_disk_layout:
  scsi0: "vm-storage:60,format=raw,discard=on,ssd=1"
amount_of_memory: 32768
number_of_vcpus: 16
ip_range:
  - start: 10.24.3.220
    end: 10.24.3.222
starting_number: 1
vm_name: prod-swfs-master
vm_description: "Production SeaweedFS Master node"
