---
# Machine specs
scsi_disk_layout:
  scsi0: "vm-storage:60,format=raw,discard=on,ssd=1"
  scsi1: "vm-storage:4T,format=raw,discard=on,ssd=1"
amount_of_memory: 65536
number_of_vcpus: 12
ip_range:
  - start: 10.24.3.170
    end: 10.24.3.170
starting_number: 1
vm_name: prod-db-backup
vm_description: "Production PostgreSQL Backup (pgBackRest)"
