---
# Machine specs
scsi_disk_layout:
  scsi0: "vm-storage:400,format=raw,discard=on,ssd=1"
amount_of_memory: 98304
minimum_memory: 8192
number_of_vcpus: 96
ip_range:
  - start: 10.24.0.90
    end: 10.24.0.97
starting_number: 1
vm_name: prod-ehi-delta
vm_description: "Production EHI Delta node"
