---
# Machine specs
scsi_disk_layout:
  scsi0: "vm-storage:100,format=raw,discard=on,ssd=1"
amount_of_memory: 65536
number_of_vcpus: 8
ip_range:
  - start: 10.24.3.180
    end: 10.24.3.185
starting_number: 5
vm_name: prod-redis
vm_description: "Production Redis nodes for SeaweedFS"
