---
# Machine specs
scsi_disk_layout:
  scsi0: "vm-storage:50,format=raw,discard=on"
amount_of_memory: 8192
number_of_vcpus: 8
ip_range:
  - start: 10.24.3.210
    end: 10.24.3.212
starting_number: 1
vm_name: prod-gitea
vm_description: "Production Gitea Git service"
