---
# Machine specs
scsi_disk_layout:
  scsi0: "vm-storage:64,format=raw,discard=on,ssd=1"
  scsi1: "vm-storage:25,format=raw,discard=on,ssd=1"
  scsi2: "vm-storage:25,format=raw,discard=on,ssd=1"
amount_of_memory: 16384
number_of_vcpus: 8
ip_range:
  - start: 10.24.0.11
    end: 10.24.0.13
starting_number: 1
vm_name: prod-ebi-k8s-m
vm_description: "Production EBI Kubernetes Control Plane node"