---
# Machine specs
scsi_disk_layout:
  scsi0: "vm-storage:100,format=raw,discard=on,ssd=1"
amount_of_memory: 16384
number_of_vcpus: 4
ip_range:
  - start: 10.24.0.101
    end: 10.24.0.107
starting_number: 1
vm_name: prod-phos-k8s-m
vm_description: "Production Phosphophyllite Kubernetes Control Plane node"