---
# Machine specs
scsi_disk_layout:
  scsi0: "vm-storage:50,format=raw,discard=on,ssd=1"
amount_of_memory: 8192
number_of_vcpus: 8
ip_range:
  - start: 10.24.0.8
    end: 10.24.0.10
starting_number: 1
vm_name: prod-bastion
vm_description: "Production Bastion (Netbird) hosts"
