---
# Machine specs
scsi_disk_layout:
  scsi0: "vm-storage:50,format=raw"
amount_of_memory: 65536
minimum_memory: 16384
number_of_vcpus: 6
ip_range:
  - start: 10.24.0.111
    end: 10.24.0.150
starting_number: 1
vm_name: prod-phos-k8s-w
vm_description: "Production Phosphophyllite Kubernetes Worker node"