---
# Machine specs
scsi_disk_layout:
  scsi0: "vm-storage:50,format=raw,discard=on,ssd=1"
amount_of_memory: 6144
number_of_vcpus: 4
ip_range:
  - start: 10.24.0.33
    end: 10.24.0.33
starting_number: 1
vm_name: prod-estuary-upload
vm_description: "Production EstuaryV1 Upload Proxy"
