---
# Machine specs
scsi_disk_layout:
  scsi0: "vm-storage:50,format=raw,discard=on,ssd=1"
  scsi1: "vm-storage:100,format=raw,discard=on,ssd=1"
amount_of_memory: 16384
number_of_vcpus: 8
ip_range:
  - start: 10.24.3.1
    end: 10.24.3.3
starting_number: 1
vm_name: prod-ebi-db
vm_description: "Production EBI Database node"