---
# Machine specs
scsi_disk_layout:
  scsi0: "vm-storage:1500,format=raw,discard=on,ssd=1"
amount_of_memory: 131072
number_of_vcpus: 96
ip_range:
  - start: 10.24.3.60
    end: 10.24.3.60
starting_number: 12
vm_name: prod-shuttle
vm_description: "Production Shuttle node"
